import '@/app/globals.scss';
import DefaultLayout from '@/layouts';

export const metadata = {
    title: 'Doan Vu',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
